config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'sessions/create'
  get 'sessions/failure'
  get 'static_pages/home'
  post 'static_pages/flickr_users_images'
  get 'static_pages/flickr_users_contacts'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
require 'pp'

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default("")
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  flickr_user_id         :string
#  provider               :string
#  uid                    :string
#  oauth_token            :string
#  oauth_token_secret     :string
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:flickr]
  
  def self.from_omniauth(auth)
    Rails.logger.debug("OmniAuth Auth Hash: #{auth.pretty_inspect}")
    Rails.logger.debug("OmniAuth Auth Token: #{auth.credentials.token.pretty_inspect}")
    Rails.logger.debug("OmniAuth Auth Secret: #{auth.credentials.secret.pretty_inspect}")
    
    user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.username = auth.info.nickname
      user.password = Devise.friendly_token[0, 20]
      user.oauth_token = auth.credentials.token
      user.oauth_token_secret = auth.credentials.secret
    end
    if user.new_record?
      if user.valid?
        user.save!
      else
        Rails.logger.debug("User could not be saved: #{user.errors.full_messages}")
      end
    end
    user
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  def home
    if params[:uid] && (params[:api_method] == "fetch_photos")
      puts "******* params were fetch_photos and uid ************"
      @photos = fetch_photos("flickr.people.getPhotos")
      Rails.logger.debug(@photos)
    end
    
    if params[:uid] && (params[:api_method] == "fetch_contacts")
      puts "******* params were fetch_contacts and uid ************"
      @contacts = fetch_contacts('flickr.contacts.getList')
      Rails.logger.debug(@contacts)
    end
  end

  private
  def fetch_photos(api_method)
    flickr_service = FlickrService.new(current_user)
    flickr_service.fetch_photos(api_method)
  end
  
  def fetch_contacts(api_method)
    flickr_service = FlickrService.new(current_user)
    @contacts = flickr_service.fetch_contacts(api_method)
  end

  def static_page_params
    params.require(:static_page).permit(:uid, :username, :api_method)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController

  def flickr
    Rails.logger.debug
    # Here you handle the callback from Flickr
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication, notice: "user was persisted and signed in"
    else
      session["devise.flickr_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url, notice: "user not created"
    end
  end


  def failure
    # handle failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlickr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="m-4">
    <nav class="flex flex-row">

      <div class="home-btn">
        <% unless current_page?(root_path) %>
          <%= link_to "Home", root_path, class: "btn btn-primary w-40 mr-6" %>
        <% end %>
      </div>

      <div class="account-btns mr-6">
        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "link" %>
        <% else %>
          <div class="flex">
            <%= button_to 'Sign In', new_user_session_path, class: "btn btn-primary mr-2" %>
            <%= button_to 'Sign in with Flickr', user_flickr_omniauth_authorize_path, data: { turbo: false }, class: "inline btn btn-primary mr-2" %>
          </div>
        <% end %>
      </div>

      <div class="params mr-6">
        <p class="prose">Here's your params: <%= params %></p>
      </div>

      <div class="flash">
        <% unless flash.empty? %>
          <% if notice %>
            <p class="notice"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert"><%= alert %></p>
          <% end %>
        <% end %>
      </div>

    </nav>
  
    <main class="">
      <%= yield %>
    </main>

  </body>
</html>

app/views/static_pages/_images.html.erb
<section>
  <h1><%= flickr_user_id %>'s Photos</h1>
  <div>
    <% photos.each do |photo| %>
      <p><%= photo[:url] %></p>
      <img src="<%= photo[:url] %>" alt="photo" %>
    <% end %>
  </div>
</section>

app/views/static_pages/home.html.erb
<div class="container mx-auto mt-28 px-5 flex">
  <div class="flex flex-col">
    <div class="prose">
      <h1 class="font-bold text-4xl">StaticPages#home</h1>
      <p>Find me in app/views/static_pages/home.html.erb</p>
    </div>



    <div class="my-8">
      <%= form_with url: static_pages_home_path, method: :get, data: { turbo: false } do |f| %>
          <%= f.label "Flickr User ID:", :flickr_user_id, class: "label text-md font-bold" %>
          <%= f.text_field :uid, value: current_user.uid, class: "input input-bordered input-primary max-w-xs" %>
          <%= f.hidden_field :api_method, value: :fetch_photos %>
          <%= f.submit "Get Photos", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="my-8">
      <% if user_signed_in? %>
        <%= form_with url: static_pages_home_path, method: :get, data: { turbo: false } do |f| %>
          <%= f.hidden_field :uid, value: current_user.uid %>
          <%= f.hidden_field :api_method, value: :fetch_contacts %>
          <%= f.submit "Get My Contacts", class: "btn btn-primary" %>
        <% end %>
      <% else %>
        <%= link_to "Sign in with Flickr", user_flickr_omniauth_authorize_path, data: { turbo: false } %>
      <% end %>

      <%#= form_with url: static_pages_home_path, method: :get, local: true do |f| %>
          <%#= f.hidden_field :uid, value: current_user.uid %>
          <%#= f.submit "Get My contacts", class: "btn-primary-sm" %>
      <%# end %>
    </div>


    <div class="photos">
      <% if @photos.present? %>
        <%= render partial: 'images', locals: { photos: @photos, flickr_user_id: @flickr_user_id } %>
      <% end %>
    </div>  
    
    <div class="contacts">
      <% if @contacts.present? %>
        <%= @contacts %>
        <%#= @contacts.each do |contact| %>
          <%#= contact.username %>
        <%# end %>
      <% end %>
    </div>  
  </div>
</div>